TYPE=VIEW
query=select `book_movie_tickets`.`ve`.`Id` AS `veId`,`book_movie_tickets`.`ve`.`KhachHangId` AS `KhachHangId`,`book_movie_tickets`.`ve`.`LichChieuId` AS `LichChieuId`,`book_movie_tickets`.`ve`.`MaQR` AS `MaQR`,`book_movie_tickets`.`ve`.`MoTa` AS `MoTa`,`book_movie_tickets`.`ve`.`ThoiGiaDat` AS `ThoiGiaDat`,`book_movie_tickets`.`ve`.`total` AS `total`,`book_movie_tickets`.`ve`.`created_at` AS `created_at`,`book_movie_tickets`.`ve`.`updated_at` AS `updated_at`,`cv`.`gheId` AS `gheId`,`book_movie_tickets`.`ghe`.`Ten` AS `tenGhe`,`book_movie_tickets`.`ghe`.`Hang` AS `hangGhe`,`p`.`Ten` AS `tenPhim`,`p`.`img` AS `imgPhim`,`p`.`QuocGia` AS `quocGia`,`lc`.`Ngay` AS `ngayChieu`,`lc`.`GioBatDau` AS `GioBatDau`,`ph`.`Ten` AS `tenPhong`,`cn`.`Ten` AS `tenChinhanh` from ((((((`book_movie_tickets`.`chitietve` `cv` join `book_movie_tickets`.`ve` on(`book_movie_tickets`.`ve`.`Id` = `cv`.`veId`)) join `book_movie_tickets`.`ghe` on(`book_movie_tickets`.`ghe`.`Id` = `cv`.`gheId`)) join `book_movie_tickets`.`lichchieu` `lc` on(`lc`.`Id` = `book_movie_tickets`.`ve`.`LichChieuId`)) join `book_movie_tickets`.`phim` `p` on(`p`.`Id` = `lc`.`PhimId`)) join `book_movie_tickets`.`phong` `ph` on(`ph`.`Id` = `lc`.`PhongId`)) join `book_movie_tickets`.`chinhanh` `cn` on(`cn`.`Id` = `ph`.`ChiNhanhId`))
md5=6fb0653aaa831498dd1690a2acc3c8ff
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=0001701629597080155
create-version=2
source=SELECT\n    `book_movie_tickets`.`ve`.`Id` AS `veId`,\n    `book_movie_tickets`.`ve`.`KhachHangId` AS `KhachHangId`,\n    `book_movie_tickets`.`ve`.`LichChieuId` AS `LichChieuId`,\n    `book_movie_tickets`.`ve`.`MaQR` AS `MaQR`,\n    `book_movie_tickets`.`ve`.`MoTa` AS `MoTa`,\n    `book_movie_tickets`.`ve`.`ThoiGiaDat` AS `ThoiGiaDat`,\n    `book_movie_tickets`.`ve`.`total` AS `total`,\n    `book_movie_tickets`.`ve`.`created_at` AS `created_at`,\n    `book_movie_tickets`.`ve`.`updated_at` AS `updated_at`,\n    `cv`.`gheId` AS `gheId`,\n    `book_movie_tickets`.`ghe`.`Ten` AS `tenGhe`,\n    `book_movie_tickets`.`ghe`.`Hang` AS `hangGhe`,\n    `p`.`Ten` AS `tenPhim`,\n    `p`.`img` AS `imgPhim`,\n    `p`.`QuocGia` AS `quocGia`,\n    `lc`.`Ngay` AS `ngayChieu`,\n    `lc`.`GioBatDau` AS `GioBatDau`,\n    `ph`.`Ten` AS `tenPhong`,\n    `cn`.`Ten` AS `tenChinhanh`\nFROM\n    (\n        (\n            (\n                (\n                    (\n                        (\n                            `book_movie_tickets`.`chitietve` `cv`\n                        JOIN `book_movie_tickets`.`ve` ON\n                            (\n                                `book_movie_tickets`.`ve`.`Id` = `cv`.`veId`\n                            )\n                        )\n                    JOIN `book_movie_tickets`.`ghe` ON\n                        (\n                            `book_movie_tickets`.`ghe`.`Id` = `cv`.`gheId`\n                        )\n                    )\n                JOIN `book_movie_tickets`.`lichchieu` `lc`\n                ON\n                    (\n                        `lc`.`Id` = `book_movie_tickets`.`ve`.`LichChieuId`\n                    )\n                )\n            JOIN `book_movie_tickets`.`phim` `p`\n            ON\n                (`p`.`Id` = `lc`.`PhimId`)\n            )\n        JOIN `book_movie_tickets`.`phong` `ph`\n        ON\n            (`ph`.`Id` = `lc`.`PhongId`)\n        )\n    JOIN `book_movie_tickets`.`chinhanh` `cn`\n    ON\n        (`cn`.`Id` = `ph`.`ChiNhanhId`)\n    )
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `book_movie_tickets`.`ve`.`Id` AS `veId`,`book_movie_tickets`.`ve`.`KhachHangId` AS `KhachHangId`,`book_movie_tickets`.`ve`.`LichChieuId` AS `LichChieuId`,`book_movie_tickets`.`ve`.`MaQR` AS `MaQR`,`book_movie_tickets`.`ve`.`MoTa` AS `MoTa`,`book_movie_tickets`.`ve`.`ThoiGiaDat` AS `ThoiGiaDat`,`book_movie_tickets`.`ve`.`total` AS `total`,`book_movie_tickets`.`ve`.`created_at` AS `created_at`,`book_movie_tickets`.`ve`.`updated_at` AS `updated_at`,`cv`.`gheId` AS `gheId`,`book_movie_tickets`.`ghe`.`Ten` AS `tenGhe`,`book_movie_tickets`.`ghe`.`Hang` AS `hangGhe`,`p`.`Ten` AS `tenPhim`,`p`.`img` AS `imgPhim`,`p`.`QuocGia` AS `quocGia`,`lc`.`Ngay` AS `ngayChieu`,`lc`.`GioBatDau` AS `GioBatDau`,`ph`.`Ten` AS `tenPhong`,`cn`.`Ten` AS `tenChinhanh` from ((((((`book_movie_tickets`.`chitietve` `cv` join `book_movie_tickets`.`ve` on(`book_movie_tickets`.`ve`.`Id` = `cv`.`veId`)) join `book_movie_tickets`.`ghe` on(`book_movie_tickets`.`ghe`.`Id` = `cv`.`gheId`)) join `book_movie_tickets`.`lichchieu` `lc` on(`lc`.`Id` = `book_movie_tickets`.`ve`.`LichChieuId`)) join `book_movie_tickets`.`phim` `p` on(`p`.`Id` = `lc`.`PhimId`)) join `book_movie_tickets`.`phong` `ph` on(`ph`.`Id` = `lc`.`PhongId`)) join `book_movie_tickets`.`chinhanh` `cn` on(`cn`.`Id` = `ph`.`ChiNhanhId`))
mariadb-version=100427
